# Site settings
author: Stef Spears
title: Boot the Binary
header-img: img/home-bg.png
email: spears.sj87@gmail.com
copyright_name: Stef Spears
description: > # this means to ignore newlines until "baseurl:"
  The scenic route.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: stefdotjs
github_username:  stef-spears

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
